#!/bin/bash

VESTIGE_RPM_VERSION=$(cat src/vestige-desktop.spec | grep "Version:" | sed 's/Version:[ \t]*//g')

rm -r target
mkdir target
cp src/Makefile target/vestige-desktop-$VESTIGE_RPM_VERSION/
cp -r ../standard_edition_linux_desktop/src/hicolor target/vestige-desktop-$VESTIGE_RPM_VERSION/
cp ../standard_edition_linux_desktop/src/vestige_gtk_launcher.py target/vestige-desktop-$VESTIGE_RPM_VERSION/
chmod +x target/vestige-desktop-$VESTIGE_RPM_VERSION/vestige_gtk_launcher.py
cp ../standard_edition_linux_desktop/src/vestige.desktop target/vestige-desktop-$VESTIGE_RPM_VERSION/
find target \( -name .svn -o -name .DS_Store \) -exec rm -rf {} \;
pushd target && tar -czf vestige-desktop.tar.gz vestige-desktop-$VESTIGE_RPM_VERSION && popd
scp target/vestige-desktop.tar.gz rpmbuilder:rpmbuild/SOURCES/vestige-desktop.tar.gz
scp target/vestige-desktop.spec rpmbuilder:rpmbuild/SPECS/vestige-desktop.spec
ssh rpmbuilder rpmbuild -bb '~/rpmbuild/SPECS/vestige-desktop.spec'
scp rpmbuilder:rpmbuild/RPMS/noarch/vestige-desktop-$VESTIGE_RPM_VERSION-1.noarch.rpm target/vestige-desktop-$VESTIGE_RPM_VERSION-1.noarch.rpm
